export const EQUIPMENT_DATA = [
  { equipment: 'Port Main Engine', toBeCleared: 'To be cleared by DTTT(V)', btssc: '' },
  { equipment: 'Stbd Main Engine', toBeCleared: 'To be cleared by DTTT(V)', btssc: '' },
  { equipment: 'Gear Box (Stbd)', toBeCleared: 'SDCs.', btssc: '' },
  { equipment: 'Shaft Lock Checks', toBeCleared: '', btssc: '' },
  { equipment: 'Torsionmeter Calibration Certificate', toBeCleared: '', btssc: '' },
  { equipment: 'POL Report', toBeCleared: '', btssc: '' },
  { equipment: 'Gear Box (Port)', toBeCleared: 'SDCs.', btssc: '' },
  { equipment: 'Shafting (Port)', toBeCleared: 'SDCs.', btssc: '' },
  { equipment: 'Shafting (Stbd)', toBeCleared: 'SDCs.', btssc: '' },
  { equipment: 'CPP (Port)', toBeCleared: 'SDCs.', btssc: '' },
  { equipment: 'CPP (Stbd)', toBeCleared: '', btssc: '' },
  { equipment: 'ME Lub Oil Priming Pump 1', toBeCleared: 'To be cleared prior BT', btssc: '' },
  { equipment: 'ME Lub Oil Priming Pump 2', toBeCleared: 'To be cleared prior BT', btssc: '' },
  { equipment: 'ME Lub Oil Priming Pump 3', toBeCleared: 'To be cleared prior BT', btssc: '' },
  { equipment: 'ME Lub Oil Priming Pump 4', toBeCleared: 'To be cleared prior BT', btssc: '' },
  { equipment: 'GB LO Stand by Pump (Port)', toBeCleared: 'To be cleared prior BT', btssc: '' },
  { equipment: 'GB LO Stand by Pump (Stbd)', toBeCleared: '', btssc: '' },
  { equipment: 'GB SW Stand by Pump (Port)', toBeCleared: '', btssc: '' },
  { equipment: 'GB SW Stand by Pump (Stbd)', toBeCleared: '', btssc: '' },
  { equipment: 'CPP Stand by Pump (Port)', toBeCleared: '', btssc: '' },
  { equipment: 'CPP Stand by Pump (Stbd)', toBeCleared: '', btssc: '' },
  { equipment: 'Steering Gear', toBeCleared: '', btssc: '' },
  { equipment: 'Steering Gear Harbour Trials', toBeCleared: 'To be cleared prior BT', btssc: '' },
  { equipment: 'Steering Pump (Port)', toBeCleared: '', btssc: '' },
  { equipment: 'Steering Pump (Stbd)', toBeCleared: '', btssc: '' },
  { equipment: 'Steering Gear Sea Trials', toBeCleared: 'To be cleared prior SSC 1', btssc: '' },
  { equipment: 'Stabiliser', toBeCleared: '', btssc: '' },
  { equipment: 'Stabiliser Harbour Trials', toBeCleared: 'To be cleared prior SSC 1', btssc: '' },
  { equipment: 'Stabiliser Pump (Port)', toBeCleared: '', btssc: '' },
  { equipment: 'Stabiliser Pump (Stbd)', toBeCleared: '', btssc: '' },
  { equipment: 'Stabiliser Sea Trials', toBeCleared: 'To be cleared prior SSC 2', btssc: '' },
  { equipment: 'HPAC 1', toBeCleared: '02 HPAC to be cleared prior BT', btssc: '' },
  { equipment: 'HPAC 2', toBeCleared: '', btssc: '' },
  { equipment: 'HPAC 3', toBeCleared: '', btssc: '' },
  { equipment: 'Compressed Air System', toBeCleared: 'To be cleared prior BT', btssc: '' },
  { equipment: 'AC Plant 1', toBeCleared: 'At least 02 AC Plants to be cleared prior BT', btssc: '' },
  { equipment: 'AC Plant 2', toBeCleared: '', btssc: '' },
  { equipment: 'AC Plant 3', toBeCleared: '', btssc: '' },
  { equipment: 'AC Chilled Water Pump 1', toBeCleared: 'Two pumps to be cleared prior BT. One prior SSC 1', btssc: '' },
  { equipment: 'AC Chilled Water Pump 2', toBeCleared: '', btssc: '' },
  { equipment: 'AC Chilled Water Pump 3', toBeCleared: '', btssc: '' }
];
